# libraries
library(casebase)
library(future.apply)
library(glmnet)
library(cbSCRIP)
library(parallel)
library(tictoc)
library(tidyverse)
library(foreach)
library(survival)
library(cmprsk)
library(glue)
library(here)
library(pec)
library(CoxBoost)
library(riskRegression)

# ---------- loading prediction functions --------------
source("paper/code/prediction_functions.r")
source("notes_jmr/code/fitting_functions.R")


#function helpers

# make_title <- function(N, p, num_true, setting) {
#     desc <- settings_tbl$desc[settings_tbl$setting == setting]
#     paste0("N = ", N, ", p = ", p,  ", k = ", num_true, ", ", desc)
# }

make_run_id <- function(setting, N, p, k)
    sprintf("setting%d_N%d_p%d_k%d", setting, N, p, k)

make_fname <- function(setting, N, p, num_true) {
    paste0("brier_setting", setting,
           "_N", N, "_p", p, "_k", num_true, ".png")
}


brier_plot_fn <- function(n, p, num_true, setting,save_dir = here::here("paper","preds")){

data <- cbSCRIP:::gen_data(n = n, p = p, num_true = num_true, setting = setting, iter = 123)

beta1 <- data$beta1
beta2 <- data$beta2
train <- data$train
test <- data$test
p <- sum(grepl("^X", names(train)))  # number of X-variables

# Test time-points for Brier score 
time_points <- sort(unique(test$ftime))

#restrict test time-points outside the training
tmax <- max(train$ftime[train$fstatus != 0], na.rm = TRUE)
time_points <- time_points[ is.finite(time_points) & time_points <= tmax ]

################## Brier score casebase #########################

fit_val_min <- cv_cbSCRIP(Surv(ftime, fstatus) ~ .,
                          train,
                          nlambda = 50,
                          alpha = 0.5,
                          ratio = 50)

#----------------------------------
# Smaller lambda, within 2SE

# Fit model with Lambda(min + 2SE)
lambda_min_nc <- fit_val_min$lambda.min
lambda_min_nc_idx <- which(lambda_min_nc == fit_val_min$lambdagrid)
dev_lambda_nc <- fit_val_min$deviance_mean[lambda_min_nc_idx]
se_lambda_nc <- fit_val_min$deviance_se[lambda_min_nc_idx]

thr <- dev_lambda_nc + 2*se_lambda_nc
lambdas_2SEless <- which(fit_val_min$deviance_mean <= thr &
          fit_val_min$lambdagrid < lambda_min_nc)

if (length(lambdas_2SEless)) {
    lambda_less_penal_2se <- min(fit_val_min$lambdagrid[lambdas_2SEless])
    lambda_less_penal_2se_idx <- which.min(abs(fit_val_min$lambdagrid -
                                                   lambda_less_penal_2se))
} else {
    warning("No λ smaller than λ_min within 2 SE; using λ_min.")
    lambda_less_penal_2se <- lambda_min_nc
    lambda_less_penal_2se_idx <- lambda_min_nc_idx
}


# Fit model with smaller lambda (min + 2SE)
fit_val_min2SE <- cbSCRIP(
    cb_data = fit_val_min$cb_data, # using case-base sample generated by cv function
    alpha = 0.5,
    lambda = lambda_less_penal_2se,
    ratio = 50)

res_cb_min2SE_1 <-varsel_perc(fit_val_min2SE$coefficients[[1]][1:p, 1], 
                          beta1)

non_zero_coefs_cause1 <- which(abs(fit_val_min2SE$coefficients[[1]][1:p, 1]) > thr.b)
non_zero_coefs <- paste("X", non_zero_coefs_cause1 , sep = "")
trainnew <- cbind(train[, c(colnames(train) %in% non_zero_coefs)], ftime = (train$ftime), fstatus = train$fstatus)
testnew <- cbind(test[, c(colnames(test) %in% non_zero_coefs)], ftime = (test$ftime), fstatus = test$fstatus)


# Fit unpenalized model

model_cb <- fitSmoothHazard(fstatus ~ . + log(ftime) - fstatus, data = trainnew, ratio = 50, time = "ftime")


briercasebase <- Score(list("Case-base" = model_cb),
                      data = test,
                      formula = Hist(ftime, fstatus) ~ 1, summary = "ibs",
                      se.fit = FALSE, metrics = "Brier", contrasts = FALSE,
                      times = time_points, cause = 1)

############################# CoxBoost ########################################
optim.res <- iCoxBoost(Hist(ftime, fstatus)~., data = train, cause = 1, cv = TRUE)

cbfit <-  iCoxBoost(Hist(ftime, fstatus)~., data = train, cause = 1,
                    stepno = optim.res$cv.res$optimal.step)

# Brier score for coxboost
briercoxboost <- Score(list("CoxBoost" = cbfit),
                       data = test,
                       formula = Hist(ftime, fstatus) ~ 1, summary = "ibs", 
                       se.fit = FALSE, metrics = "Brier", contrasts = FALSE, 
                       times = time_points, cause = 1)

########################## iCR ###############################################
# Prepare data for coxph
iCS = two.i.CSlassos(data = train, nlambda = 100)

brieriCS <- Score(list("iCS" = iCS),
                  data = test,
                  formula = Hist(ftime, fstatus) ~ 1, summary = "ibs", 
                  se.fit = FALSE, metrics = "Brier", contrasts = FALSE, 
                  times = time_points, cause = 1)

###################### Aalen-Johnson #########################################
fit.aj <- prodlim(Hist(ftime,fstatus)~1,data= train)

# Aalen-Johnson 
score_aj <- Score(
  list("Aalen-Johnson" = fit.aj),
  formula = Hist(ftime, fstatus) ~ 1,
  data = test,
  times = time_points,
  summary = c("ipa"),
  metrics = c("brier"))

######################### Penalized casebase ####################################
class(fit_val_min2SE) <- "penalizedCompRisk"

brierpenCB <- Score(list("penCB" = fit_val_min2SE),
                    data = test,
                    formula = Hist(ftime, fstatus) ~ 1, summary = "ibs", 
                    se.fit = FALSE, metrics = "Brier", contrasts = FALSE, 
                    times = time_points, cause = 1)

########################## Plot brier score ######################################
# Combine scores
data_brier <- bind_rows(
  briercasebase$Brier$score %>% 
   mutate(model = as.character(model)) %>% 
    filter(model != "Null model"), 
  brierpenCB$Brier$score %>% 
    mutate(model = as.character(model)) %>% 
    filter(model != "Null model"), 
  score_aj$Brier$score %>% 
    mutate(model = as.character(model)) %>% 
    filter(model != "Null model"), 
  briercoxboost$Brier$score %>% 
    mutate(model = as.character(model)) %>% 
    filter(model != "Null model"), 
  brieriCS$Brier$score %>% 
    mutate(model = as.character(model)) %>% 
    filter(model != "Null model")
  )

# Convert into factor 
data_brier$model <- factor(data_brier$model)

levels(data_brier$model) <- c("Aalen-Johansen", "De-biased Case-base", "Boosted Fine-Gray", "iCR", "Case-base")

#data_brier$title <- "N = 400, p = 300, Non-proportional hazards"
#data_brier$title <- make_title(n, p, num_true, paste0("setting",setting))
data_brier$title <- settings_tbl$desc[settings_tbl$setting == paste0("setting",setting)]

cbPalette <- c("#808080", "#D55E00", "#CC79A7", "#56B4E9", "#E69F00")

fname <- make_fname(setting=setting, N=n, p=p, num_true=num_true)

#png(filename = here("paper", "figs", fname), res = 300, height = 12, width = 20, units = "cm") 
plot2 <- ggplot(data = data_brier, aes(x = times, y = Brier, col = model)) +
  geom_line(size = 0.5) + 
  geom_line(data = filter(data_brier, model == "De-biased Case-base"), linewidth  = 2) + 
  geom_line(data = filter(data_brier, model == "Case-base"), linewidth  = 1.5) + 
  xlab("Follow-up time (years)") +
  ylab("Brier Score") +
  labs(color = "Models") +
  theme_bw() + scale_colour_brewer(palette = "Dark2") +
  labs(y = "Brier Score for Cause 1 Predictions") +
  scale_colour_manual(values=cbPalette) + facet_grid(. ~ title)

#------- save plot ------------------------------
ggsave(here("paper", "figs", fname), plot2,
       width = 20, height = 12, units = "cm", dpi = 300)  # save file

#------- save data and objects ------------------
run_id <- make_run_id(setting, n, p, num_true)
dir.create(save_dir, recursive = TRUE, showWarnings = FALSE)
rds_path <- file.path(save_dir, paste0("results_", run_id, ".rds"))

results <- list(
    meta = list(N = n, p = p, k = num_true, setting = setting,
                time_points = time_points, seed = 123,
                fname = fname),
    data = list(train = train, test = test, beta1 = beta1, beta2 = beta2),
    models = list(
        fit_val_min = fit_val_min,
        fit_val_min2SE = fit_val_min2SE,
        model_cb = model_cb,
        cbfit = cbfit,
        iCS = iCS,
        fit_aj = fit.aj
    ),
    scores = list(
        briercasebase = briercasebase,
        brierpenCB = brierpenCB,
        briercoxboost = briercoxboost,
        brieriCS = brieriCS,
        score_aj = score_aj
    ),
    brier_table = data_brier,
    plot = plot2
)

saveRDS(results, rds_path, compress = "xz")
message("Saved run to: ", rds_path)

invisible(results) 
}

plot_grid_fn <- function(N,p,k){
# Reading figures
img_dir <- here::here("paper","figs")
files <- file.path(img_dir, sprintf("brier_setting%d_N%d_p%d_k%d.png", 1:5, N, p, k))
out   <- file.path(img_dir, sprintf("brier_grid_N%d_p%d_k%d.png", N, p, k))

dir.create(dirname(out), recursive = TRUE, showWarnings = FALSE)

# --- SAVE TO FILE ---
grDevices::png(out, width = 2400, height = 1600, res = 200)
grid::grid.newpage()
vp <- grid::viewport(layout = grid::grid.layout(2, 3))
grid::pushViewport(vp)

for (i in seq_along(files)) {
    r <- ((i - 1) %/% 3) + 1
    c <- ((i - 1) %%  3) + 1
    img <- png::readPNG(files[i])                # note: png::readPNG => no library(png) needed
    grid::grid.raster(img, vp = grid::viewport(layout.pos.row = r, layout.pos.col = c))
}
}
